In [1]:
2 + 2

4

In [2]:
4 * 2

8

In [3]:
4 ** 2

16

In [4]:
4 * * 2

SyntaxError: invalid syntax (3917798244.py, line 1)

In [7]:
# this is a comment--it's just a note for the programmer
# it's not code
2 + 2  # adds 2 and 2

4

In [8]:
pi = 3.1415927

In [9]:
pi * (5 ** 2)

78.5398175

In [10]:
x = 5

In [11]:
x

5

In [12]:
x * 2

10

In [13]:
x = 42  # overwrites the value of x!
y = 43
x + y

85

In [14]:
x = x + 1  # RHS gets evaluated first and then put into LHS
x

43

In [15]:
subtotal = 9.99
tax = subtotal * 0.0875
subtotal + tax

10.864125

# Function calls

In [16]:
# ^ this is called Markdown. It's a "programming language" to make pretty documents!

In [17]:
max(2, 3)

3

In [19]:
round(subtotal + tax, 2)

10.86

In [20]:
abs(-42)

42

# Libraries

In [21]:
sin(pi)

NameError: name 'sin' is not defined

In [22]:
# ^ we have to import the math library to use its stuff

In [23]:
import math

In [24]:
math.sqrt(2)

1.4142135623730951

In [26]:
round(math.sin(math.pi), 5)

0.0

In [27]:
math.log?

Docstring:
log(x, [base=math.e])
Return the logarithm of x to the given base.

If the base is not specified, returns the natural logarithm (base e) of x.
Type:      builtin_function_or_method

In [28]:
math.log(32, 2)

5.0

In [29]:
from math import sqrt
sqrt(2)

1.4142135623730951

# Tables

In [30]:
from datascience import *
# the * imports everything into the "top level" so I don't have to say datascience.______

In [31]:
Table.read_table?

Signature: Table.read_table(filepath_or_buffer, *args, **vargs)
Docstring:
Read a table from a file or web address.

Args:
    filepath_or_buffer -- string or file handle / StringIO; The string
                      could be a URL. Valid URL schemes include http,
                      ftp, s3, and file.

Returns:
    a table read from argument

Example:

>>> Table.read_table('https://www.inferentialthinking.com/data/sat2014.csv')
State        | Participation Rate | Critical Reading | Math | Writing | Combined
North Dakota | 2.3                | 612              | 620  | 584     | 1816
Illinois     | 4.6                | 599              | 616  | 587     | 1802
Iowa         | 3.1                | 605              | 611  | 578     | 1794
South Dakota | 2.9                | 604              | 609  | 579     | 1792
Minnesota    | 5.9                | 598              | 610  | 578     | 1786
Michigan     | 3.8                | 593              | 610  | 581     | 1784
Wisconsin    | 3.9                | 596              | 608  | 578     | 1782
Missouri     | 4.2                | 595              | 597  | 579     | 1771
Wyoming      | 3.3                | 590              | 599  | 573     | 1762
Kansas       | 5.3                | 591              | 596  | 566     | 1753
... (41 rows omitted)

File:      \\?\c:\users\ln015\appdata\roaming\jupyterlab-desktop\jlab_server\lib\site-packages\datascience\tables.py
Type:      method

In [33]:
cones = Table.read_table('data/cones.csv')
cones

Flavor     | Color       | Price
strawberry | pink        | 3.55
chocolate  | light brown | 4.75
chocolate  | dark brown  | 5.25
vanilla    | white       | 3.5
strawberry | pink        | 5.25
chocolate  | dark brown  | 5.25
bubblegum  | pink        | 4.75

In [34]:
cones.show(2)

In [35]:
cones.show()

In [36]:
cones.select('Flavor')

Flavor
strawberry
chocolate
chocolate
vanilla
strawberry
chocolate
bubblegum

In [37]:
cones  # hasn't changed

Flavor     | Color       | Price
strawberry | pink        | 3.55
chocolate  | light brown | 4.75
chocolate  | dark brown  | 5.25
vanilla    | white       | 3.5
strawberry | pink        | 5.25
chocolate  | dark brown  | 5.25
bubblegum  | pink        | 4.75

In [40]:
cones.select('Flavor', "Color")

Flavor     | Color
strawberry | pink
chocolate  | light brown
chocolate  | dark brown
vanilla    | white
strawberry | pink
chocolate  | dark brown
bubblegum  | pink

In [42]:
cones_no_price = cones.drop('Price')
cones_no_price

Flavor     | Color
strawberry | pink
chocolate  | light brown
chocolate  | dark brown
vanilla    | white
strawberry | pink
chocolate  | dark brown
bubblegum  | pink

In [43]:
cones

Flavor     | Color       | Price
strawberry | pink        | 3.55
chocolate  | light brown | 4.75
chocolate  | dark brown  | 5.25
vanilla    | white       | 3.5
strawberry | pink        | 5.25
chocolate  | dark brown  | 5.25
bubblegum  | pink        | 4.75

In [45]:
cones.sort('Price')

Flavor     | Color       | Price
vanilla    | white       | 3.5
strawberry | pink        | 3.55
chocolate  | light brown | 4.75
bubblegum  | pink        | 4.75
chocolate  | dark brown  | 5.25
strawberry | pink        | 5.25
chocolate  | dark brown  | 5.25

In [46]:
cones.sort('Price', descending=True)

Flavor     | Color       | Price
chocolate  | dark brown  | 5.25
strawberry | pink        | 5.25
chocolate  | dark brown  | 5.25
chocolate  | light brown | 4.75
bubblegum  | pink        | 4.75
strawberry | pink        | 3.55
vanilla    | white       | 3.5

In [48]:
cones.where('Flavor', 'chocolate')

Flavor    | Color       | Price
chocolate | light brown | 4.75
chocolate | dark brown  | 5.25
chocolate | dark brown  | 5.25

In [49]:
pokemon = Table.read_table('data/pokemon.csv')
pokemon

abilities                   | against_bug | against_dark | against_dragon | against_electric | against_fairy | against_fight | against_fire | against_flying | against_ghost | against_grass | against_ground | against_ice | against_normal | against_poison | against_psychic | against_rock | against_steel | against_water | attack | base_egg_steps | base_happiness | base_total | capture_rate | classfication       | defense | experience_growth | height_m | hp   | japanese_name    | name       | percentage_male | pokedex_number | sp_attack | sp_defense | speed | type1 | type2  | weight_kg | generation | is_legendary
['Overgrow', 'Chlorophyll'] | 1           | 1            | 1              | 0.5              | 0.5           | 0.5           | 2            | 2              | 1             | 0.25          | 1              | 2           | 1              | 1              | 2               | 1            | 1             | 0.5           | 49     | 5120           | 70             | 318        | 45           | Seed Pokémon        | 49      | 1059860           | 0.7      | 45   | Fushigidaneフシギダネ | Bulbasaur  | 88.1            | 1              | 65        | 65         | 45    | grass | poison | 6.9       | 1          | 0
['Overgrow', 'Chlorophyll'] | 1           | 1            | 1              | 0.5              | 0.5           | 0.5           | 2            | 2              | 1             | 0.25          | 1              | 2           | 1              | 1              | 2               | 1            | 1             | 0.5           | 62     | 5120           | 70             | 405        | 45           | Seed Pokémon        | 63      | 1059860           | 1        | 60   | Fushigisouフシギソウ  | Ivysaur    | 88.1            | 2              | 80        | 80         | 60    | grass | poison | 13        | 1          | 0
['Overgrow', 'Chlorophyll'] | 1           | 1            | 1              | 0.5              | 0.5           | 0.5           | 2            | 2              | 1             | 0.25          | 1              | 2           | 1              | 1              | 2               | 1            | 1             | 0.5           | 100    | 5120           | 70             | 625        | 45           | Seed Pokémon        | 123     | 1059860           | 2        | 80   | Fushigibanaフシギバナ | Venusaur   | 88.1            | 3              | 122       | 120        | 80    | grass | poison | 100       | 1          | 0
['Blaze', 'Solar Power']    | 0.5         | 1            | 1              | 1                | 0.5           | 1             | 0.5          | 1              | 1             | 0.5           | 2              | 0.5         | 1              | 1              | 1               | 2            | 0.5           | 2             | 52     | 5120           | 70             | 309        | 45           | Lizard Pokémon      | 43      | 1059860           | 0.6      | 39   | Hitokageヒトカゲ     | Charmander | 88.1            | 4              | 60        | 50         | 65    | fire  | nan    | 8.5       | 1          | 0
['Blaze', 'Solar Power']    | 0.5         | 1            | 1              | 1                | 0.5           | 1             | 0.5          | 1              | 1             | 0.5           | 2              | 0.5         | 1              | 1              | 1               | 2            | 0.5           | 2             | 64     | 5120           | 70             | 405        | 45           | Flame Pokémon       | 58      | 1059860           | 1.1      | 58   | Lizardoリザード      | Charmeleon | 88.1            | 5              | 80        | 65         | 80    | fire  | nan    | 19        | 1          | 0
['Blaze', 'Solar Power']    | 0.25        | 1            | 1              | 2                | 0.5           | 0.5           | 0.5          | 1              | 1             | 0.25          | 0              | 1           | 1              | 1              | 1               | 4            | 0.5           | 2             | 104    | 5120           | 70             | 634        | 45           | Flame Pokémon       | 78      | 1059860           | 1.7      | 78   | Lizardonリザードン    | Charizard  | 88.1            | 6              | 159       | 115        | 100   | fire  | flying | 90.5      | 1          | 0
['Torrent', 'Rain Dish']    | 1           | 1            | 1              | 2                | 1             | 1             | 0.5          | 1              | 1             | 2             | 1              | 0.5         | 1              | 1              | 1               | 1            | 0.5           | 0.5           | 48     | 5120           | 70             | 314        | 45           | Tiny Turtle Pokémon | 65      | 1059860           | 0.5      | 44   | Zenigameゼニガメ     | Squirtle   | 88.1            | 7              | 50        | 64         | 43    | water | nan    | 9         | 1          | 0
['Torrent', 'Rain Dish']    | 1           | 1            | 1              | 2                | 1             | 1             | 0.5          | 1              | 1             | 2             | 1              | 0.5         | 1              | 1              | 1               | 1            | 0.5           | 0.5           | 63     | 5120           | 70             | 405        | 45           | Turtle Pokémon      | 80      | 1059860           | 1        | 59   | Kameilカメール       | Wartortle  | 88.1            | 8              | 65        | 80         | 58    | water | nan    | 22.5      | 1          | 0
['Torrent', 'Rain Dish']    | 1           | 1            | 1              | 2                | 1             | 1             | 0.5          | 1              | 1             | 2             | 1              | 0.5         | 1              | 1              | 1               | 1            | 0.5           | 0.5           | 103    | 5120           | 70             | 630        | 45           | Shellfish Pokémon   | 120     | 1059860           | 1.6      | 79   | Kamexカメックス       | Blastoise  | 88.1            | 9              | 135       | 115        | 78    | water | nan    | 85.5      | 1          | 0
['Shield Dust', 'Run Away'] | 1           | 1            | 1              | 1                | 1             | 0.5           | 2            | 2              | 1             | 0.5           | 0.5            | 1           | 1              | 1              | 1               | 2            | 1             | 1             | 30     | 3840           | 70             | 195        | 255          | Worm Pokémon        | 35      | 1000000           | 0.3      | 45   | Caterpieキャタピー    | Caterpie   | 50              | 10             | 20        | 20         | 45    | bug   | nan    | 2.9       | 1          | 0
... (791 rows omitted)

In [50]:
pokemon.where('name', 'Pikachu')

abilities                  | against_bug | against_dark | against_dragon | against_electric | against_fairy | against_fight | against_fire | against_flying | against_ghost | against_grass | against_ground | against_ice | against_normal | against_poison | against_psychic | against_rock | against_steel | against_water | attack | base_egg_steps | base_happiness | base_total | capture_rate | classfication | defense | experience_growth | height_m | hp   | japanese_name | name    | percentage_male | pokedex_number | sp_attack | sp_defense | speed | type1    | type2 | weight_kg | generation | is_legendary
['Static', 'Lightningrod'] | 1           | 1            | 1              | 0.5              | 1             | 1             | 1            | 0.5            | 1             | 1             | 2              | 1           | 1              | 1              | 1               | 1            | 0.5           | 1             | 55     | 2560           | 70             | 320        | 190          | Mouse Pokémon | 40      | 1000000           | 0.4      | 35   | Pikachuピカチュウ  | Pikachu | 50              | 25             | 50        | 50         | 90    | electric | nan   | 6         | 1          | 0

In [51]:
pokemon.where('type1', 'electric')

abilities                                  | against_bug | against_dark | against_dragon | against_electric | against_fairy | against_fight | against_fire | against_flying | against_ghost | against_grass | against_ground | against_ice | against_normal | against_poison | against_psychic | against_rock | against_steel | against_water | attack | base_egg_steps | base_happiness | base_total | capture_rate | classfication      | defense | experience_growth | height_m | hp   | japanese_name   | name       | percentage_male | pokedex_number | sp_attack | sp_defense | speed | type1    | type2    | weight_kg | generation | is_legendary
['Static', 'Lightningrod']                 | 1           | 1            | 1              | 0.5              | 1             | 1             | 1            | 0.5            | 1             | 1             | 2              | 1           | 1              | 1              | 1               | 1            | 0.5           | 1             | 55     | 2560           | 70             | 320        | 190          | Mouse Pokémon      | 40      | 1000000           | 0.4      | 35   | Pikachuピカチュウ    | Pikachu    | 50              | 25             | 50        | 50         | 90    | electric | nan      | 6         | 1          | 0
['Static', 'Lightningrod', 'Surge Surfer'] | 1           | 1            | 1              | 0.5              | 1             | 1             | 1            | 0.5            | 1             | 1             | 2              | 1           | 1              | 1              | 1               | 1            | 0.5           | 1             | 85     | 2560           | 70             | 485        | 75           | Mouse Pokémon      | 50      | 1000000           | nan      | 60   | Raichuライチュウ     | Raichu     | 50              | 26             | 95        | 85         | 110   | electric | electric | nan       | 1          | 0
['Magnet Pull', 'Sturdy', 'Analytic']      | 0.5         | 1            | 0.5            | 0.5              | 0.5           | 2             | 2            | 0.25           | 1             | 0.5           | 4              | 0.5         | 0.5            | 0              | 0.5             | 0.5          | 0.25          | 1             | 35     | 5120           | 70             | 325        | 190          | Magnet Pokémon     | 70      | 1000000           | 0.3      | 25   | Coilコイル         | Magnemite  | nan             | 81             | 95        | 55         | 45    | electric | steel    | 6         | 1          | 0
['Magnet Pull', 'Sturdy', 'Analytic']      | 0.5         | 1            | 0.5            | 0.5              | 0.5           | 2             | 2            | 0.25           | 1             | 0.5           | 4              | 0.5         | 0.5            | 0              | 0.5             | 0.5          | 0.25          | 1             | 60     | 5120           | 70             | 465        | 60           | Magnet Pokémon     | 95      | 1000000           | 1        | 50   | Rarecoilレアコイル   | Magneton   | nan             | 82             | 120       | 70         | 70    | electric | steel    | 60        | 1          | 0
['Soundproof', 'Static', 'Aftermath']      | 1           | 1            | 1              | 0.5              | 1             | 1             | 1            | 0.5            | 1             | 1             | 2              | 1           | 1              | 1              | 1               | 1            | 0.5           | 1             | 30     | 5120           | 70             | 330        | 190          | Ball Pokémon       | 50      | 1000000           | 0.5      | 40   | Biriridamaビリリダマ | Voltorb    | nan             | 100            | 55        | 55         | 100   | electric | nan      | 10.4      | 1          | 0
['Soundproof', 'Static', 'Aftermath']      | 1           | 1            | 1              | 0.5              | 1             | 1             | 1            | 0.5            | 1             | 1             | 2              | 1           | 1              | 1              | 1               | 1            | 0.5           | 1             | 50     | 5120           | 70             | 490        | 60           | Ball Pokémon       | 70      | 1000000           | 1.2      | 60   | Marumineマルマイン   | Electrode  | nan             | 101            | 80        | 80         | 150   | electric | nan      | 66.6      | 1          | 0
['Static', 'Vital Spirit']                 | 1           | 1            | 1              | 0.5              | 1             | 1             | 1            | 0.5            | 1             | 1             | 2              | 1           | 1              | 1              | 1               | 1            | 0.5           | 1             | 83     | 6400           | 70             | 490        | 45           | Electric Pokémon   | 57      | 1000000           | 1.1      | 65   | Elebooエレブー      | Electabuzz | 75.4            | 125            | 95        | 85         | 105   | electric | nan      | 30        | 1          | 0
['Volt Absorb', 'Quick Feet']              | 1           | 1            | 1              | 0.5              | 1             | 1             | 1            | 0.5            | 1             | 1             | 2              | 1           | 1              | 1              | 1               | 1            | 0.5           | 1             | 65     | 8960           | 70             | 525        | 45           | Lightning Pokémon  | 60      | 1000000           | 0.8      | 65   | Thundersサンダース   | Jolteon    | 88.1            | 135            | 110       | 95         | 130   | electric | nan      | 24.5      | 1          | 0
['Pressure', 'Static']                     | 0.5         | 1            | 1              | 1                | 1             | 0.5           | 1            | 0.5            | 1             | 0.5           | 0              | 2           | 1              | 1              | 1               | 2            | 0.5           | 1             | 90     | 20480          | 35             | 580        | 3            | Electric Pokémon   | 85      | 1250000           | 1.6      | 90   | Thunderサンダー     | Zapdos     | nan             | 145            | 125       | 90         | 100   | electric | flying   | 52.6      | 1          | 1
['Static', 'Lightningrod']                 | 1           | 1            | 1              | 0.5              | 1             | 1             | 1            | 0.5            | 1             | 1             | 2              | 1           | 1              | 1              | 1               | 1            | 0.5           | 1             | 40     | 2560           | 70             | 205        | 190          | Tiny Mouse Pokémon | 15      | 1000000           | 0.3      | 20   | Pichuピチュー       | Pichu      | 50              | 172            | 35        | 35         | 60    | electric | nan      | 2         | 2          | 0
... (29 rows omitted)

In [53]:
gen1 = pokemon.where('generation', 1)

In [57]:
gen1.sort('attack', descending=True)

abilities                                      | against_bug | against_dark | against_dragon | against_electric | against_fairy | against_fight | against_fire | against_flying | against_ghost | against_grass | against_ground | against_ice | against_normal | against_poison | against_psychic | against_rock | against_steel | against_water | attack | base_egg_steps | base_happiness | base_total | capture_rate | classfication      | defense | experience_growth | height_m | hp   | japanese_name | name       | percentage_male | pokedex_number | sp_attack | sp_defense | speed | type1    | type2  | weight_kg | generation | is_legendary
['Hyper Cutter', 'Mold Breaker', 'Moxie']      | 1           | 1            | 1              | 1                | 1             | 0.5           | 2            | 2              | 1             | 0.5           | 0.5            | 1           | 1              | 1              | 1               | 2            | 1             | 1             | 155    | 6400           | 70             | 600        | 45           | Stagbeetle Pokémon | 120     | 1250000           | 1.5      | 65   | Kailiosカイロス   | Pinsir     | 50              | 127            | 65        | 90         | 105   | bug      | nan    | 55        | 1          | 0
['Intimidate', 'Moxie']                        | 0.5         | 1            | 1              | 4                | 1             | 0.5           | 0.5          | 1              | 1             | 1             | 0              | 1           | 1              | 1              | 1               | 2            | 0.5           | 0.5           | 155    | 1280           | 70             | 640        | 45           | Atrocious Pokémon  | 109     | 1250000           | 6.5      | 95   | Gyaradosギャラドス | Gyarados   | 50              | 130            | 70        | 130        | 81    | water    | flying | 235       | 1          | 0
['Swarm', 'Sniper']                            | 0.5         | 1            | 1              | 1                | 0.5           | 0.25          | 2            | 2              | 1             | 0.25          | 1              | 1           | 1              | 0.5            | 2               | 2            | 1             | 1             | 150    | 3840           | 70             | 495        | 45           | Poison Bee Pokémon | 40      | 1000000           | 1        | 65   | Spearスピアー     | Beedrill   | 50              | 15             | 15        | 80         | 145   | bug      | poison | 29.5      | 1          | 0
['Pressure', 'Unnerve']                        | 2           | 2            | 1              | 1                | 1             | 0.5           | 1            | 1              | 2             | 1             | 1              | 1           | 1              | 1              | 0.5             | 1            | 1             | 1             | 150    | 30720          | 0              | 780        | 3            | Genetic Pokémon    | 70      | 1250000           | 2        | 106  | Mewtwoミュウツー   | Mewtwo     | nan             | 150            | 194       | 120        | 140   | psychic  | nan    | 122       | 1          | 1
['Rock Head', 'Pressure', 'Unnerve']           | 0.5         | 1            | 1              | 2                | 1             | 1             | 0.5          | 0.5            | 1             | 1             | 0              | 2           | 0.5            | 0.5            | 1               | 2            | 2             | 2             | 135    | 8960           | 70             | 615        | 45           | Fossil Pokémon     | 85      | 1250000           | 1.8      | 80   | Pteraプテラ      | Aerodactyl | 88.1            | 142            | 70        | 95         | 150   | rock     | flying | 59        | 1          | 0
['Inner Focus', 'Multiscale']                  | 0.5         | 1            | 2              | 1                | 2             | 0.5           | 0.5          | 1              | 1             | 0.25          | 0              | 4           | 1              | 1              | 1               | 2            | 1             | 0.5           | 134    | 10240          | 35             | 600        | 45           | Dragon Pokémon     | 95      | 1250000           | 2.2      | 91   | Kairyuカイリュー   | Dragonite  | 50              | 149            | 100       | 100        | 80    | dragon   | flying | 210       | 1          | 0
['Guts', 'No Guard', 'Steadfast']              | 0.5         | 0.5          | 1              | 1                | 2             | 1             | 1            | 2              | 1             | 1             | 1              | 1           | 1              | 1              | 2               | 0.5          | 1             | 1             | 130    | 5120           | 70             | 505        | 45           | Superpower Pokémon | 80      | 1059860           | 1.6      | 90   | Kairikyカイリキー  | Machamp    | 75.4            | 68             | 65        | 85         | 55    | fighting | nan    | 130       | 1          | 0
['Hyper Cutter', 'Shell Armor', 'Sheer Force'] | 1           | 1            | 1              | 2                | 1             | 1             | 0.5          | 1              | 1             | 2             | 1              | 0.5         | 1              | 1              | 1               | 1            | 0.5           | 0.5           | 130    | 5120           | 70             | 475        | 60           | Pincer Pokémon     | 115     | 1000000           | 1.3      | 55   | Kinglerキングラー  | Kingler    | 50              | 99             | 50        | 50         | 75    | water    | nan    | 60        | 1          | 0
['Lightningrod', 'Rock Head', 'Reckless']      | 1           | 1            | 1              | 0                | 1             | 2             | 0.5          | 0.5            | 1             | 4             | 2              | 2           | 0.5            | 0.25           | 1               | 0.5          | 2             | 4             | 130    | 5120           | 70             | 485        | 60           | Drill Pokémon      | 120     | 1250000           | 1.9      | 105  | Sidonサイドン     | Rhydon     | 50              | 112            | 45        | 45         | 40    | ground   | rock   | 120       | 1          | 0
['Flash Fire', 'Guts']                         | 0.5         | 1            | 1              | 1                | 0.5           | 1             | 0.5          | 1              | 1             | 0.5           | 2              | 0.5         | 1              | 1              | 1               | 2            | 0.5           | 2             | 130    | 8960           | 70             | 525        | 45           | Flame Pokémon      | 60      | 1000000           | 0.9      | 65   | Boosterブースター  | Flareon    | 88.1            | 136            | 95        | 110        | 65    | fire     | nan    | 25        | 1          | 0
... (141 rows omitted)

In [59]:
gen1.sort('attack', descending=True).select('name', 'type1', 'attack')

name       | type1    | attack
Pinsir     | bug      | 155
Gyarados   | water    | 155
Beedrill   | bug      | 150
Mewtwo     | psychic  | 150
Aerodactyl | rock     | 135
Dragonite  | dragon   | 134
Machamp    | fighting | 130
Kingler    | water    | 130
Rhydon     | ground   | 130
Flareon    | fire     | 130
... (141 rows omitted)

In [ ]:
# question: find the top 8 generation 2 pokemon with the highest defense